/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface CampaignAim {
    'aim': string;
  }
  interface CampaignPage {
    'campaignId': number;
    'logo': string;
    'name': string;
  }
  interface ChildComponent {
    'number': number;
  }
  interface FlexContainer {
    'alignx': string;
    'aligny': String;
    'direction': String;
    'mobColumn': Boolean;
    'wrap': Boolean;
  }
  interface FullwidthBeigeStrip {}
  interface FullwidthStrip {
    'background': string;
    'height': string;
  }
  interface GetInvolved {}
  interface MyComponent {
    /**
    * The first name
    */
    'first': string;
    /**
    * The last name
    */
    'last': string;
    /**
    * The middle name
    */
    'middle': string;
  }
  interface PageContent {}
  interface ParentComponent {
    'number': number;
  }
  interface QuickLink {
    'to': string;
  }
  interface QuickLinks {
    'title': string;
  }
  interface SecondComponent {
    'animal': string;
  }
}

declare global {


  interface HTMLCampaignAimElement extends Components.CampaignAim, HTMLStencilElement {}
  const HTMLCampaignAimElement: {
    prototype: HTMLCampaignAimElement;
    new (): HTMLCampaignAimElement;
  };

  interface HTMLCampaignPageElement extends Components.CampaignPage, HTMLStencilElement {}
  const HTMLCampaignPageElement: {
    prototype: HTMLCampaignPageElement;
    new (): HTMLCampaignPageElement;
  };

  interface HTMLChildComponentElement extends Components.ChildComponent, HTMLStencilElement {}
  const HTMLChildComponentElement: {
    prototype: HTMLChildComponentElement;
    new (): HTMLChildComponentElement;
  };

  interface HTMLFlexContainerElement extends Components.FlexContainer, HTMLStencilElement {}
  const HTMLFlexContainerElement: {
    prototype: HTMLFlexContainerElement;
    new (): HTMLFlexContainerElement;
  };

  interface HTMLFullwidthBeigeStripElement extends Components.FullwidthBeigeStrip, HTMLStencilElement {}
  const HTMLFullwidthBeigeStripElement: {
    prototype: HTMLFullwidthBeigeStripElement;
    new (): HTMLFullwidthBeigeStripElement;
  };

  interface HTMLFullwidthStripElement extends Components.FullwidthStrip, HTMLStencilElement {}
  const HTMLFullwidthStripElement: {
    prototype: HTMLFullwidthStripElement;
    new (): HTMLFullwidthStripElement;
  };

  interface HTMLGetInvolvedElement extends Components.GetInvolved, HTMLStencilElement {}
  const HTMLGetInvolvedElement: {
    prototype: HTMLGetInvolvedElement;
    new (): HTMLGetInvolvedElement;
  };

  interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {}
  const HTMLMyComponentElement: {
    prototype: HTMLMyComponentElement;
    new (): HTMLMyComponentElement;
  };

  interface HTMLPageContentElement extends Components.PageContent, HTMLStencilElement {}
  const HTMLPageContentElement: {
    prototype: HTMLPageContentElement;
    new (): HTMLPageContentElement;
  };

  interface HTMLParentComponentElement extends Components.ParentComponent, HTMLStencilElement {}
  const HTMLParentComponentElement: {
    prototype: HTMLParentComponentElement;
    new (): HTMLParentComponentElement;
  };

  interface HTMLQuickLinkElement extends Components.QuickLink, HTMLStencilElement {}
  const HTMLQuickLinkElement: {
    prototype: HTMLQuickLinkElement;
    new (): HTMLQuickLinkElement;
  };

  interface HTMLQuickLinksElement extends Components.QuickLinks, HTMLStencilElement {}
  const HTMLQuickLinksElement: {
    prototype: HTMLQuickLinksElement;
    new (): HTMLQuickLinksElement;
  };

  interface HTMLSecondComponentElement extends Components.SecondComponent, HTMLStencilElement {}
  const HTMLSecondComponentElement: {
    prototype: HTMLSecondComponentElement;
    new (): HTMLSecondComponentElement;
  };
  interface HTMLElementTagNameMap {
    'campaign-aim': HTMLCampaignAimElement;
    'campaign-page': HTMLCampaignPageElement;
    'child-component': HTMLChildComponentElement;
    'flex-container': HTMLFlexContainerElement;
    'fullwidth-beige-strip': HTMLFullwidthBeigeStripElement;
    'fullwidth-strip': HTMLFullwidthStripElement;
    'get-involved': HTMLGetInvolvedElement;
    'my-component': HTMLMyComponentElement;
    'page-content': HTMLPageContentElement;
    'parent-component': HTMLParentComponentElement;
    'quick-link': HTMLQuickLinkElement;
    'quick-links': HTMLQuickLinksElement;
    'second-component': HTMLSecondComponentElement;
  }
}

declare namespace LocalJSX {
  interface CampaignAim {
    'aim'?: string;
  }
  interface CampaignPage {
    'campaignId'?: number;
    'logo'?: string;
    'name'?: string;
  }
  interface ChildComponent {
    'number'?: number;
  }
  interface FlexContainer {
    'alignx'?: string;
    'aligny'?: String;
    'direction'?: String;
    'mobColumn'?: Boolean;
    'wrap'?: Boolean;
  }
  interface FullwidthBeigeStrip {}
  interface FullwidthStrip {
    'background'?: string;
    'height'?: string;
  }
  interface GetInvolved {}
  interface MyComponent {
    /**
    * The first name
    */
    'first'?: string;
    /**
    * The last name
    */
    'last'?: string;
    /**
    * The middle name
    */
    'middle'?: string;
  }
  interface PageContent {}
  interface ParentComponent {
    'number'?: number;
  }
  interface QuickLink {
    'to'?: string;
  }
  interface QuickLinks {
    'title'?: string;
  }
  interface SecondComponent {
    'animal'?: string;
  }

  interface IntrinsicElements {
    'campaign-aim': CampaignAim;
    'campaign-page': CampaignPage;
    'child-component': ChildComponent;
    'flex-container': FlexContainer;
    'fullwidth-beige-strip': FullwidthBeigeStrip;
    'fullwidth-strip': FullwidthStrip;
    'get-involved': GetInvolved;
    'my-component': MyComponent;
    'page-content': PageContent;
    'parent-component': ParentComponent;
    'quick-link': QuickLink;
    'quick-links': QuickLinks;
    'second-component': SecondComponent;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'campaign-aim': LocalJSX.CampaignAim & JSXBase.HTMLAttributes<HTMLCampaignAimElement>;
      'campaign-page': LocalJSX.CampaignPage & JSXBase.HTMLAttributes<HTMLCampaignPageElement>;
      'child-component': LocalJSX.ChildComponent & JSXBase.HTMLAttributes<HTMLChildComponentElement>;
      'flex-container': LocalJSX.FlexContainer & JSXBase.HTMLAttributes<HTMLFlexContainerElement>;
      'fullwidth-beige-strip': LocalJSX.FullwidthBeigeStrip & JSXBase.HTMLAttributes<HTMLFullwidthBeigeStripElement>;
      'fullwidth-strip': LocalJSX.FullwidthStrip & JSXBase.HTMLAttributes<HTMLFullwidthStripElement>;
      'get-involved': LocalJSX.GetInvolved & JSXBase.HTMLAttributes<HTMLGetInvolvedElement>;
      'my-component': LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
      'page-content': LocalJSX.PageContent & JSXBase.HTMLAttributes<HTMLPageContentElement>;
      'parent-component': LocalJSX.ParentComponent & JSXBase.HTMLAttributes<HTMLParentComponentElement>;
      'quick-link': LocalJSX.QuickLink & JSXBase.HTMLAttributes<HTMLQuickLinkElement>;
      'quick-links': LocalJSX.QuickLinks & JSXBase.HTMLAttributes<HTMLQuickLinksElement>;
      'second-component': LocalJSX.SecondComponent & JSXBase.HTMLAttributes<HTMLSecondComponentElement>;
    }
  }
}


