/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface AccordionContainer {}
  interface AccordionDropdown {
    'header': string;
  }
  interface CampaignAim {}
  interface CampaignAimContainer {
    'campaignname': string;
  }
  interface CampaignNews {
    'newsid': string;
  }
  interface CampaignPage {
    'campaignId': number;
    'name': string;
  }
  interface CampaignTabs {
    'facebook': string;
    'newsid': string;
    'socials': string;
    'strategydoc': string;
  }
  interface ChildComponent {
    'number': number;
  }
  interface ElectionsFooter {}
  interface FlexContainer {
    'alignx': string;
    'aligny': string;
    'direction': string;
    'mobcolumn': boolean;
    'wrap': boolean;
  }
  interface FullwidthBeigeStrip {}
  interface FullwidthStrip {
    'color': string;
    'height': string;
  }
  interface GetInvolved {
    'typeform': string;
  }
  interface InnerTabContent {
    'active': boolean;
    'name': string;
  }
  interface InnerTabHeader {
    'active': boolean;
    'id': string;
    'name': string;
  }
  interface InnerTabsContainer {
    'innertab': boolean;
  }
  interface MyComponent {
    /**
    * The first name
    */
    'first': string;
    /**
    * The last name
    */
    'last': string;
    /**
    * The middle name
    */
    'middle': string;
  }
  interface NewsCard {
    'newslink': string;
    'newstitle': string;
  }
  interface PageContent {}
  interface ParentComponent {
    'number': number;
  }
  interface PrimaryButton {
    'to': string;
  }
  interface PurpleButton {
    'link': string;
    'whitetext': boolean;
  }
  interface QuickLink {
    'to': string;
  }
  interface QuickLinks {
    'name': string;
  }
  interface SecondComponent {
    'animal': string;
  }
  interface ShowSupport {}
  interface SupportOption {
    'heading': string;
    'supportname': string;
  }
  interface SupportProgress {
    'current': any;
    'maxtotal': any;
    'supportname': string;
  }
  interface TabContent {
    'active': boolean;
    'name': string;
  }
  interface TabHeader {
    'active': boolean;
    'id': string;
    'name': string;
  }
  interface TabsContainer {
    'innertab': boolean;
  }
  interface VideoBanner {
    'url': string;
  }
}

declare global {


  interface HTMLAccordionContainerElement extends Components.AccordionContainer, HTMLStencilElement {}
  const HTMLAccordionContainerElement: {
    prototype: HTMLAccordionContainerElement;
    new (): HTMLAccordionContainerElement;
  };

  interface HTMLAccordionDropdownElement extends Components.AccordionDropdown, HTMLStencilElement {}
  const HTMLAccordionDropdownElement: {
    prototype: HTMLAccordionDropdownElement;
    new (): HTMLAccordionDropdownElement;
  };

  interface HTMLCampaignAimElement extends Components.CampaignAim, HTMLStencilElement {}
  const HTMLCampaignAimElement: {
    prototype: HTMLCampaignAimElement;
    new (): HTMLCampaignAimElement;
  };

  interface HTMLCampaignAimContainerElement extends Components.CampaignAimContainer, HTMLStencilElement {}
  const HTMLCampaignAimContainerElement: {
    prototype: HTMLCampaignAimContainerElement;
    new (): HTMLCampaignAimContainerElement;
  };

  interface HTMLCampaignNewsElement extends Components.CampaignNews, HTMLStencilElement {}
  const HTMLCampaignNewsElement: {
    prototype: HTMLCampaignNewsElement;
    new (): HTMLCampaignNewsElement;
  };

  interface HTMLCampaignPageElement extends Components.CampaignPage, HTMLStencilElement {}
  const HTMLCampaignPageElement: {
    prototype: HTMLCampaignPageElement;
    new (): HTMLCampaignPageElement;
  };

  interface HTMLCampaignTabsElement extends Components.CampaignTabs, HTMLStencilElement {}
  const HTMLCampaignTabsElement: {
    prototype: HTMLCampaignTabsElement;
    new (): HTMLCampaignTabsElement;
  };

  interface HTMLChildComponentElement extends Components.ChildComponent, HTMLStencilElement {}
  const HTMLChildComponentElement: {
    prototype: HTMLChildComponentElement;
    new (): HTMLChildComponentElement;
  };

  interface HTMLElectionsFooterElement extends Components.ElectionsFooter, HTMLStencilElement {}
  const HTMLElectionsFooterElement: {
    prototype: HTMLElectionsFooterElement;
    new (): HTMLElectionsFooterElement;
  };

  interface HTMLFlexContainerElement extends Components.FlexContainer, HTMLStencilElement {}
  const HTMLFlexContainerElement: {
    prototype: HTMLFlexContainerElement;
    new (): HTMLFlexContainerElement;
  };

  interface HTMLFullwidthBeigeStripElement extends Components.FullwidthBeigeStrip, HTMLStencilElement {}
  const HTMLFullwidthBeigeStripElement: {
    prototype: HTMLFullwidthBeigeStripElement;
    new (): HTMLFullwidthBeigeStripElement;
  };

  interface HTMLFullwidthStripElement extends Components.FullwidthStrip, HTMLStencilElement {}
  const HTMLFullwidthStripElement: {
    prototype: HTMLFullwidthStripElement;
    new (): HTMLFullwidthStripElement;
  };

  interface HTMLGetInvolvedElement extends Components.GetInvolved, HTMLStencilElement {}
  const HTMLGetInvolvedElement: {
    prototype: HTMLGetInvolvedElement;
    new (): HTMLGetInvolvedElement;
  };

  interface HTMLInnerTabContentElement extends Components.InnerTabContent, HTMLStencilElement {}
  const HTMLInnerTabContentElement: {
    prototype: HTMLInnerTabContentElement;
    new (): HTMLInnerTabContentElement;
  };

  interface HTMLInnerTabHeaderElement extends Components.InnerTabHeader, HTMLStencilElement {}
  const HTMLInnerTabHeaderElement: {
    prototype: HTMLInnerTabHeaderElement;
    new (): HTMLInnerTabHeaderElement;
  };

  interface HTMLInnerTabsContainerElement extends Components.InnerTabsContainer, HTMLStencilElement {}
  const HTMLInnerTabsContainerElement: {
    prototype: HTMLInnerTabsContainerElement;
    new (): HTMLInnerTabsContainerElement;
  };

  interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {}
  const HTMLMyComponentElement: {
    prototype: HTMLMyComponentElement;
    new (): HTMLMyComponentElement;
  };

  interface HTMLNewsCardElement extends Components.NewsCard, HTMLStencilElement {}
  const HTMLNewsCardElement: {
    prototype: HTMLNewsCardElement;
    new (): HTMLNewsCardElement;
  };

  interface HTMLPageContentElement extends Components.PageContent, HTMLStencilElement {}
  const HTMLPageContentElement: {
    prototype: HTMLPageContentElement;
    new (): HTMLPageContentElement;
  };

  interface HTMLParentComponentElement extends Components.ParentComponent, HTMLStencilElement {}
  const HTMLParentComponentElement: {
    prototype: HTMLParentComponentElement;
    new (): HTMLParentComponentElement;
  };

  interface HTMLPrimaryButtonElement extends Components.PrimaryButton, HTMLStencilElement {}
  const HTMLPrimaryButtonElement: {
    prototype: HTMLPrimaryButtonElement;
    new (): HTMLPrimaryButtonElement;
  };

  interface HTMLPurpleButtonElement extends Components.PurpleButton, HTMLStencilElement {}
  const HTMLPurpleButtonElement: {
    prototype: HTMLPurpleButtonElement;
    new (): HTMLPurpleButtonElement;
  };

  interface HTMLQuickLinkElement extends Components.QuickLink, HTMLStencilElement {}
  const HTMLQuickLinkElement: {
    prototype: HTMLQuickLinkElement;
    new (): HTMLQuickLinkElement;
  };

  interface HTMLQuickLinksElement extends Components.QuickLinks, HTMLStencilElement {}
  const HTMLQuickLinksElement: {
    prototype: HTMLQuickLinksElement;
    new (): HTMLQuickLinksElement;
  };

  interface HTMLSecondComponentElement extends Components.SecondComponent, HTMLStencilElement {}
  const HTMLSecondComponentElement: {
    prototype: HTMLSecondComponentElement;
    new (): HTMLSecondComponentElement;
  };

  interface HTMLShowSupportElement extends Components.ShowSupport, HTMLStencilElement {}
  const HTMLShowSupportElement: {
    prototype: HTMLShowSupportElement;
    new (): HTMLShowSupportElement;
  };

  interface HTMLSupportOptionElement extends Components.SupportOption, HTMLStencilElement {}
  const HTMLSupportOptionElement: {
    prototype: HTMLSupportOptionElement;
    new (): HTMLSupportOptionElement;
  };

  interface HTMLSupportProgressElement extends Components.SupportProgress, HTMLStencilElement {}
  const HTMLSupportProgressElement: {
    prototype: HTMLSupportProgressElement;
    new (): HTMLSupportProgressElement;
  };

  interface HTMLTabContentElement extends Components.TabContent, HTMLStencilElement {}
  const HTMLTabContentElement: {
    prototype: HTMLTabContentElement;
    new (): HTMLTabContentElement;
  };

  interface HTMLTabHeaderElement extends Components.TabHeader, HTMLStencilElement {}
  const HTMLTabHeaderElement: {
    prototype: HTMLTabHeaderElement;
    new (): HTMLTabHeaderElement;
  };

  interface HTMLTabsContainerElement extends Components.TabsContainer, HTMLStencilElement {}
  const HTMLTabsContainerElement: {
    prototype: HTMLTabsContainerElement;
    new (): HTMLTabsContainerElement;
  };

  interface HTMLVideoBannerElement extends Components.VideoBanner, HTMLStencilElement {}
  const HTMLVideoBannerElement: {
    prototype: HTMLVideoBannerElement;
    new (): HTMLVideoBannerElement;
  };
  interface HTMLElementTagNameMap {
    'accordion-container': HTMLAccordionContainerElement;
    'accordion-dropdown': HTMLAccordionDropdownElement;
    'campaign-aim': HTMLCampaignAimElement;
    'campaign-aim-container': HTMLCampaignAimContainerElement;
    'campaign-news': HTMLCampaignNewsElement;
    'campaign-page': HTMLCampaignPageElement;
    'campaign-tabs': HTMLCampaignTabsElement;
    'child-component': HTMLChildComponentElement;
    'elections-footer': HTMLElectionsFooterElement;
    'flex-container': HTMLFlexContainerElement;
    'fullwidth-beige-strip': HTMLFullwidthBeigeStripElement;
    'fullwidth-strip': HTMLFullwidthStripElement;
    'get-involved': HTMLGetInvolvedElement;
    'inner-tab-content': HTMLInnerTabContentElement;
    'inner-tab-header': HTMLInnerTabHeaderElement;
    'inner-tabs-container': HTMLInnerTabsContainerElement;
    'my-component': HTMLMyComponentElement;
    'news-card': HTMLNewsCardElement;
    'page-content': HTMLPageContentElement;
    'parent-component': HTMLParentComponentElement;
    'primary-button': HTMLPrimaryButtonElement;
    'purple-button': HTMLPurpleButtonElement;
    'quick-link': HTMLQuickLinkElement;
    'quick-links': HTMLQuickLinksElement;
    'second-component': HTMLSecondComponentElement;
    'show-support': HTMLShowSupportElement;
    'support-option': HTMLSupportOptionElement;
    'support-progress': HTMLSupportProgressElement;
    'tab-content': HTMLTabContentElement;
    'tab-header': HTMLTabHeaderElement;
    'tabs-container': HTMLTabsContainerElement;
    'video-banner': HTMLVideoBannerElement;
  }
}

declare namespace LocalJSX {
  interface AccordionContainer {}
  interface AccordionDropdown {
    'header'?: string;
  }
  interface CampaignAim {}
  interface CampaignAimContainer {
    'campaignname'?: string;
  }
  interface CampaignNews {
    'newsid'?: string;
  }
  interface CampaignPage {
    'campaignId'?: number;
    'name'?: string;
  }
  interface CampaignTabs {
    'facebook'?: string;
    'newsid'?: string;
    'socials'?: string;
    'strategydoc'?: string;
  }
  interface ChildComponent {
    'number'?: number;
  }
  interface ElectionsFooter {}
  interface FlexContainer {
    'alignx'?: string;
    'aligny'?: string;
    'direction'?: string;
    'mobcolumn'?: boolean;
    'wrap'?: boolean;
  }
  interface FullwidthBeigeStrip {}
  interface FullwidthStrip {
    'color'?: string;
    'height'?: string;
  }
  interface GetInvolved {
    'typeform'?: string;
  }
  interface InnerTabContent {
    'active'?: boolean;
    'name'?: string;
  }
  interface InnerTabHeader {
    'active'?: boolean;
    'id'?: string;
    'name'?: string;
    'onSelectInnerTab'?: (event: CustomEvent<any>) => void;
  }
  interface InnerTabsContainer {
    'innertab'?: boolean;
  }
  interface MyComponent {
    /**
    * The first name
    */
    'first'?: string;
    /**
    * The last name
    */
    'last'?: string;
    /**
    * The middle name
    */
    'middle'?: string;
  }
  interface NewsCard {
    'newslink'?: string;
    'newstitle'?: string;
  }
  interface PageContent {}
  interface ParentComponent {
    'number'?: number;
  }
  interface PrimaryButton {
    'to'?: string;
  }
  interface PurpleButton {
    'link'?: string;
    'whitetext'?: boolean;
  }
  interface QuickLink {
    'to'?: string;
  }
  interface QuickLinks {
    'name'?: string;
  }
  interface SecondComponent {
    'animal'?: string;
  }
  interface ShowSupport {}
  interface SupportOption {
    'heading'?: string;
    'supportname'?: string;
  }
  interface SupportProgress {
    'current'?: any;
    'maxtotal'?: any;
    'supportname'?: string;
  }
  interface TabContent {
    'active'?: boolean;
    'name'?: string;
  }
  interface TabHeader {
    'active'?: boolean;
    'id'?: string;
    'name'?: string;
    'onSelectTab'?: (event: CustomEvent<any>) => void;
  }
  interface TabsContainer {
    'innertab'?: boolean;
  }
  interface VideoBanner {
    'url'?: string;
  }

  interface IntrinsicElements {
    'accordion-container': AccordionContainer;
    'accordion-dropdown': AccordionDropdown;
    'campaign-aim': CampaignAim;
    'campaign-aim-container': CampaignAimContainer;
    'campaign-news': CampaignNews;
    'campaign-page': CampaignPage;
    'campaign-tabs': CampaignTabs;
    'child-component': ChildComponent;
    'elections-footer': ElectionsFooter;
    'flex-container': FlexContainer;
    'fullwidth-beige-strip': FullwidthBeigeStrip;
    'fullwidth-strip': FullwidthStrip;
    'get-involved': GetInvolved;
    'inner-tab-content': InnerTabContent;
    'inner-tab-header': InnerTabHeader;
    'inner-tabs-container': InnerTabsContainer;
    'my-component': MyComponent;
    'news-card': NewsCard;
    'page-content': PageContent;
    'parent-component': ParentComponent;
    'primary-button': PrimaryButton;
    'purple-button': PurpleButton;
    'quick-link': QuickLink;
    'quick-links': QuickLinks;
    'second-component': SecondComponent;
    'show-support': ShowSupport;
    'support-option': SupportOption;
    'support-progress': SupportProgress;
    'tab-content': TabContent;
    'tab-header': TabHeader;
    'tabs-container': TabsContainer;
    'video-banner': VideoBanner;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'accordion-container': LocalJSX.AccordionContainer & JSXBase.HTMLAttributes<HTMLAccordionContainerElement>;
      'accordion-dropdown': LocalJSX.AccordionDropdown & JSXBase.HTMLAttributes<HTMLAccordionDropdownElement>;
      'campaign-aim': LocalJSX.CampaignAim & JSXBase.HTMLAttributes<HTMLCampaignAimElement>;
      'campaign-aim-container': LocalJSX.CampaignAimContainer & JSXBase.HTMLAttributes<HTMLCampaignAimContainerElement>;
      'campaign-news': LocalJSX.CampaignNews & JSXBase.HTMLAttributes<HTMLCampaignNewsElement>;
      'campaign-page': LocalJSX.CampaignPage & JSXBase.HTMLAttributes<HTMLCampaignPageElement>;
      'campaign-tabs': LocalJSX.CampaignTabs & JSXBase.HTMLAttributes<HTMLCampaignTabsElement>;
      'child-component': LocalJSX.ChildComponent & JSXBase.HTMLAttributes<HTMLChildComponentElement>;
      'elections-footer': LocalJSX.ElectionsFooter & JSXBase.HTMLAttributes<HTMLElectionsFooterElement>;
      'flex-container': LocalJSX.FlexContainer & JSXBase.HTMLAttributes<HTMLFlexContainerElement>;
      'fullwidth-beige-strip': LocalJSX.FullwidthBeigeStrip & JSXBase.HTMLAttributes<HTMLFullwidthBeigeStripElement>;
      'fullwidth-strip': LocalJSX.FullwidthStrip & JSXBase.HTMLAttributes<HTMLFullwidthStripElement>;
      'get-involved': LocalJSX.GetInvolved & JSXBase.HTMLAttributes<HTMLGetInvolvedElement>;
      'inner-tab-content': LocalJSX.InnerTabContent & JSXBase.HTMLAttributes<HTMLInnerTabContentElement>;
      'inner-tab-header': LocalJSX.InnerTabHeader & JSXBase.HTMLAttributes<HTMLInnerTabHeaderElement>;
      'inner-tabs-container': LocalJSX.InnerTabsContainer & JSXBase.HTMLAttributes<HTMLInnerTabsContainerElement>;
      'my-component': LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
      'news-card': LocalJSX.NewsCard & JSXBase.HTMLAttributes<HTMLNewsCardElement>;
      'page-content': LocalJSX.PageContent & JSXBase.HTMLAttributes<HTMLPageContentElement>;
      'parent-component': LocalJSX.ParentComponent & JSXBase.HTMLAttributes<HTMLParentComponentElement>;
      'primary-button': LocalJSX.PrimaryButton & JSXBase.HTMLAttributes<HTMLPrimaryButtonElement>;
      'purple-button': LocalJSX.PurpleButton & JSXBase.HTMLAttributes<HTMLPurpleButtonElement>;
      'quick-link': LocalJSX.QuickLink & JSXBase.HTMLAttributes<HTMLQuickLinkElement>;
      'quick-links': LocalJSX.QuickLinks & JSXBase.HTMLAttributes<HTMLQuickLinksElement>;
      'second-component': LocalJSX.SecondComponent & JSXBase.HTMLAttributes<HTMLSecondComponentElement>;
      'show-support': LocalJSX.ShowSupport & JSXBase.HTMLAttributes<HTMLShowSupportElement>;
      'support-option': LocalJSX.SupportOption & JSXBase.HTMLAttributes<HTMLSupportOptionElement>;
      'support-progress': LocalJSX.SupportProgress & JSXBase.HTMLAttributes<HTMLSupportProgressElement>;
      'tab-content': LocalJSX.TabContent & JSXBase.HTMLAttributes<HTMLTabContentElement>;
      'tab-header': LocalJSX.TabHeader & JSXBase.HTMLAttributes<HTMLTabHeaderElement>;
      'tabs-container': LocalJSX.TabsContainer & JSXBase.HTMLAttributes<HTMLTabsContainerElement>;
      'video-banner': LocalJSX.VideoBanner & JSXBase.HTMLAttributes<HTMLVideoBannerElement>;
    }
  }
}


