/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AcademicCandidateDisplay {
        "data": any;
    }
    interface AccordionContainer {
    }
    interface AccordionDropdown {
        "header": string;
    }
    interface AddVarsityScores {
        "year": string;
    }
    interface CampaignAim {
    }
    interface CampaignAimContainer {
        "campaignname": string;
    }
    interface CampaignNews {
        "newsid": string;
    }
    interface CampaignPage {
        "campaignId": number;
        "name": string;
    }
    interface CampaignTabs {
        "facebook": string;
        "newsid": string;
        "socials": string;
        "strategydoc": string;
    }
    interface CandidateDisplay {
        "data": any;
    }
    interface CandidateUpload {
        /**
          * MSL ELections ID
         */
        "electionid": string;
        /**
          * The JSON generated from the browser-side uploaded excel spreadsheet
         */
        "spreadsheetdata": any;
        /**
          * Either 'candidates' or 'results'. Will set the firebase url and key map
         */
        "stage": string;
    }
    interface CloudinaryApp {
        "public_id": string;
    }
    interface CreateVarsityData {
        "allowcreate": boolean;
        "allowupdate": boolean;
        "msltag": string;
        "test": boolean;
        "year": string;
    }
    interface DesktopHide {
        /**
          * In addition to hiding all children content in screens desktop + bigger, this will hide content in screens tablet + bigger
         */
        "hidetablet": boolean;
    }
    interface ElectionsCandidates {
        /**
          * A string lof either Faculties or Association search terms, separated by the | sign. PLEASE NOTE: The name will be used to filter all roles, as well as be used for the Tab Header title
         */
        "academicgroups": any;
        /**
          * The primary acrtive tab that will be open on page load
         */
        "activeid": string;
        /**
          * The election ID from MSL!
         */
        "electionid": string;
        /**
          * A string of exact role names for network officers, separated by the | sign
         */
        "networkofficers": any;
        /**
          * Set to true to display results data. False to display All Candidates
         */
        "results": boolean;
        /**
          * A string of exact role names for student officers, separated by the | sign
         */
        "studentofficers": any;
    }
    interface ElectionsFooter {
    }
    interface EventsCardsModal {
    }
    interface FlexContainer {
        /**
          * The same as the 'justify-content' flex property along the x axis
         */
        "alignx": string;
        /**
          * The same as the 'align-items' flex property along the y axis
         */
        "aligny": string;
        /**
          * Set the flex direction: column, reverse-column, row, reverse-row
         */
        "direction": string;
        /**
          * Ensure the container stretches the full width and height of parent container
         */
        "fillcontainer": boolean;
        /**
          * In mobile display in column direction - NOT YET RELEASED
         */
        "mobcolumn": boolean;
        /**
          * If the parent container element needs to be an <ul> list element
         */
        "renderlist": boolean;
        /**
          * Add flex-wrap to flex items
         */
        "wrap": boolean;
    }
    interface FullBio {
        "data": any;
    }
    interface FullwidthBeigeStrip {
    }
    interface FullwidthStrip {
        "color": string;
        "height": string;
    }
    interface GalleryThumbnail {
        "active": boolean;
        "cardheight": string;
        "emitid": string;
        "image": string;
        "videotitle": string;
    }
    interface GalleryThumbnailStacked {
        "active": boolean;
        "cardheight": string;
        "emitid": string;
        "image": string;
        "videotitle": string;
    }
    interface GetInvolved {
        "typeform": string;
    }
    interface GridLanding {
    }
    interface GridLandingItem {
        "height": string;
        "label": string;
        "width": string;
    }
    interface ImageFitContainer {
        "alt": string;
        "classes": string;
        "src": string;
    }
    interface ImageSliderAuto {
        "classes": string;
        /**
          * A string of images
         */
        "images": string[];
        "interval": number;
    }
    interface ImageText {
        /**
          * The title at the top of the text
         */
        "heading": string;
        /**
          * The image link (get from Cloudinary)
         */
        "image": string;
        /**
          * Animate the image (scale in) on scroll
         */
        "imagezoom": boolean;
        /**
          * Set the margin for the card
         */
        "margin": string;
        /**
          * Applies to MOBILE / TABLET <780px screens only. Paragraph and heading sizes reduced
         */
        "smalltext": boolean;
        /**
          * Switch the side the image is on
         */
        "switch": boolean;
        /**
          * The paragraph text
         */
        "text": string;
        /**
          * Choose the colour for the paragraph text
         */
        "textcolour": string;
    }
    interface InnerTabContent {
        "active": boolean;
        "name": string;
    }
    interface InnerTabHeader {
        "active": boolean;
        "name": string;
    }
    interface InnerTabsContainer {
        "innertab": boolean;
    }
    interface KclsuButton {
        /**
          * Centers the button in the page
         */
        "center": boolean;
        /**
          * Makes the link download
         */
        "download": boolean;
        /**
          * Event Listener name
         */
        "emitid": string;
        /**
          * Give the button a fixed width
         */
        "fixedwidth": string;
        /**
          * Adds icon to the page
         */
        "icon": string;
        /**
          * The URL to link to
         */
        "link": string;
        /**
          * specifiy a margin, otherwise uses default
         */
        "margin": string;
        /**
          * Opens the link in a new tab
         */
        "newtab": boolean;
        /**
          * Make the button a secondary purple button
         */
        "purple": boolean;
        /**
          * Give the button rounded corners
         */
        "rounded": boolean;
        /**
          * Make the button small
         */
        "small": boolean;
        /**
          * The text for the button
         */
        "text": string;
        /**
          * Makes the button very small
         */
        "verysmall": boolean;
    }
    interface KclsuCountdown {
        /**
          * The date to countdown to. Must match date string format
         */
        "date": string;
        /**
          * Optional: set a fixed font-size for tablet, desktop and wider.
         */
        "fontsize": any;
        /**
          * The text beneath the countdown
         */
        "text": any;
        /**
          * Optional: set a colour for the text beneath the countdown.
         */
        "textcolour": any;
    }
    interface KclsuModal {
        /**
          * This will allow a user to click away and hide the modal when open
         */
        "autoexit": boolean;
        /**
          * Set position to absolute or other. Defaults to fixed
         */
        "position": string;
        /**
          * Controls when the modal is open and visible or not
         */
        "show": boolean;
    }
    interface KclsuSearch {
        /**
          * If searching an custom web component, provide the name of the atrribute to query
         */
        "attr": string;
        /**
          * The container of the search result / search field, used to hide the element from results. Can be a tag, class or id
         */
        "containerselector": string;
        /**
          * The text inside the search input, which disappears once a user starts typing
         */
        "placeholdertext": string;
        /**
          * If searching an HTML element, provide the element's selector - tag, class or id
         */
        "selector": string;
    }
    interface KclsuTabsContainer {
    }
    interface LabelCard {
        /**
          * If a button included, the link for the button
         */
        "buttonlink": string;
        /**
          * If a button included, the text for the button
         */
        "buttontitle": string;
        "cardheight": string;
        /**
          * The main title of the card
         */
        "cardtitle": string;
        /**
          * The main title of the card
         */
        "highlightText": boolean;
        "image": string;
        /**
          * The link for the card - NOT for the button
         */
        "link": string;
        /**
          * If image to be displayed on right hand side
         */
        "reverse": boolean;
        "smallestheight": boolean;
        "smallheading": boolean;
        /**
          * The sub text beneath the title
         */
        "text": string;
    }
    interface LastYearScores {
    }
    interface LazyImage {
        /**
          * Image will scale into view
         */
        "animatein": boolean;
        /**
          * If setting width for mobile and desktop, use width property for mobile and this property for desktop
         */
        "desktopwidth": string;
        /**
          * Use standard CSS values to set a focus area on the image. EG 'center left'
         */
        "focusarea": string;
        "image": string;
        /**
          * A width for the image in pixels
         */
        "width": string;
    }
    interface LoadingSpinner {
        "show": boolean;
    }
    interface MobileHide {
        /**
          * In addition to hiding all children in screens mobile + smaller, this will hide content in screens tablet + smaller
         */
        "hidetablet": boolean;
    }
    interface ModalBackdrop {
        "showbg": boolean;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface NewsCard {
        "newslink": string;
        "newstitle": string;
    }
    interface PageContent {
    }
    interface PresetCard {
        "dimensions": string;
        "presetid": string;
        "presetname": string;
    }
    interface PresetControls {
    }
    interface PrimaryButton {
        "to": string;
    }
    interface ProfileCard {
        /**
          * The text for the primary text link bottom left
         */
        "cta": string;
        /**
          * The ID string for click events. Only applies to card's bottom right link- DEVELOPER USE
         */
        "emitid": string;
        /**
          * The image URL
         */
        "image": string;
        /**
          * The URL link for the primary text link on the bottom left of the card
         */
        "link": string;
        /**
          * The title for the card - usually a full name
         */
        "name": string;
        /**
          * A sub heading - usually a position or field title
         */
        "position": string;
        /**
          * The text for the secondary text link bottom right
         */
        "secondcta": string;
        /**
          * A second URL link for the bottom right of the card
         */
        "secondlink": string;
    }
    interface ProfileCardLayout {
    }
    interface ProfileLogoCard {
        /**
          * The text title of the card
         */
        "cardtitle": string;
        /**
          * The background image URL
         */
        "image": string;
        /**
          * Specify which part of the image you want to focus - top, bottom, right, left, center
         */
        "imagefocus": string;
        /**
          * The URL link for the the card
         */
        "link": string;
        /**
          * The logo image URL 150x150px
         */
        "logo": string;
        /**
          * OPTIONAL - if you are using a transparent text icon and need to set a background colour
         */
        "logocolour": string;
    }
    interface ProfileTabs {
        /**
          * Specify Tab ID you want to keep open by default
         */
        "activeid": string;
        /**
          * The URL of the database to fetch profiles from (firebase)
         */
        "database": string;
        /**
          * Array with child arrays containing Tab Heading, Tab ID, and Text(optional)
         */
        "headings": any;
    }
    interface PurpleButton {
        "link": string;
        "whitetext": boolean;
    }
    interface QuickLink {
        "to": string;
    }
    interface QuickLinks {
        "name": string;
    }
    interface ShowSupport {
    }
    interface SupportOption {
        "heading": string;
        "supportname": string;
    }
    interface SupportProgress {
        "current": any;
        "maxtotal": any;
        "supportname": string;
    }
    interface TabContent {
        "active": boolean;
        "name": string;
    }
    interface TabHeader {
        "active": boolean;
        "index": string;
        "name": string;
    }
    interface TabsContainer {
        "innertab": boolean;
    }
    interface TextCard {
        /**
          * The purple heading in the card
         */
        "cardtitle": string;
        /**
          * The Url link you want to link to
         */
        "link": string;
        /**
          * Any extra text. If you want it to be empty, add empty string value:  ""
         */
        "subtext": string;
    }
    interface UserLogin {
        /**
          * The name of the database area. For example: projectx
         */
        "database": string;
    }
    interface VarsityLanding {
        "currentDate": {
            weekday: string;
            day: any;
            month: string;
            year: any;
            hours: any;
            minutes: any;
        };
        "year": string;
    }
    interface VarsityNextMatches {
        "data": any;
    }
    interface VarsityRace {
        "data": any;
        "target": number;
    }
    interface VarsityTotalScore {
        "scores": any;
    }
    interface VarsityUpcoming {
        "data": any;
        "showall": boolean;
    }
    interface VarsityWeather {
    }
    interface VideoBanner {
        "url": string;
    }
    interface VideoEmbed {
        /**
          * The id of the Youtube Video - found in the URL eg youtube.com/watch?v={VIDEO_ID}
         */
        "embedid": any;
        /**
          * The URL of the Youtube video you want to display - CURRENTLY NOT WORKING
         */
        "url": string;
    }
    interface VideoGallery {
        /**
          * The Youtube URL for any given playlist
         */
        "playlist": any;
    }
    interface VideoGalleryStacked {
        /**
          * The Youtube URL for any given playlist
         */
        "playlist": any;
    }
}
declare global {
    interface HTMLAcademicCandidateDisplayElement extends Components.AcademicCandidateDisplay, HTMLStencilElement {
    }
    var HTMLAcademicCandidateDisplayElement: {
        prototype: HTMLAcademicCandidateDisplayElement;
        new (): HTMLAcademicCandidateDisplayElement;
    };
    interface HTMLAccordionContainerElement extends Components.AccordionContainer, HTMLStencilElement {
    }
    var HTMLAccordionContainerElement: {
        prototype: HTMLAccordionContainerElement;
        new (): HTMLAccordionContainerElement;
    };
    interface HTMLAccordionDropdownElement extends Components.AccordionDropdown, HTMLStencilElement {
    }
    var HTMLAccordionDropdownElement: {
        prototype: HTMLAccordionDropdownElement;
        new (): HTMLAccordionDropdownElement;
    };
    interface HTMLAddVarsityScoresElement extends Components.AddVarsityScores, HTMLStencilElement {
    }
    var HTMLAddVarsityScoresElement: {
        prototype: HTMLAddVarsityScoresElement;
        new (): HTMLAddVarsityScoresElement;
    };
    interface HTMLCampaignAimElement extends Components.CampaignAim, HTMLStencilElement {
    }
    var HTMLCampaignAimElement: {
        prototype: HTMLCampaignAimElement;
        new (): HTMLCampaignAimElement;
    };
    interface HTMLCampaignAimContainerElement extends Components.CampaignAimContainer, HTMLStencilElement {
    }
    var HTMLCampaignAimContainerElement: {
        prototype: HTMLCampaignAimContainerElement;
        new (): HTMLCampaignAimContainerElement;
    };
    interface HTMLCampaignNewsElement extends Components.CampaignNews, HTMLStencilElement {
    }
    var HTMLCampaignNewsElement: {
        prototype: HTMLCampaignNewsElement;
        new (): HTMLCampaignNewsElement;
    };
    interface HTMLCampaignPageElement extends Components.CampaignPage, HTMLStencilElement {
    }
    var HTMLCampaignPageElement: {
        prototype: HTMLCampaignPageElement;
        new (): HTMLCampaignPageElement;
    };
    interface HTMLCampaignTabsElement extends Components.CampaignTabs, HTMLStencilElement {
    }
    var HTMLCampaignTabsElement: {
        prototype: HTMLCampaignTabsElement;
        new (): HTMLCampaignTabsElement;
    };
    interface HTMLCandidateDisplayElement extends Components.CandidateDisplay, HTMLStencilElement {
    }
    var HTMLCandidateDisplayElement: {
        prototype: HTMLCandidateDisplayElement;
        new (): HTMLCandidateDisplayElement;
    };
    interface HTMLCandidateUploadElement extends Components.CandidateUpload, HTMLStencilElement {
    }
    var HTMLCandidateUploadElement: {
        prototype: HTMLCandidateUploadElement;
        new (): HTMLCandidateUploadElement;
    };
    interface HTMLCloudinaryAppElement extends Components.CloudinaryApp, HTMLStencilElement {
    }
    var HTMLCloudinaryAppElement: {
        prototype: HTMLCloudinaryAppElement;
        new (): HTMLCloudinaryAppElement;
    };
    interface HTMLCreateVarsityDataElement extends Components.CreateVarsityData, HTMLStencilElement {
    }
    var HTMLCreateVarsityDataElement: {
        prototype: HTMLCreateVarsityDataElement;
        new (): HTMLCreateVarsityDataElement;
    };
    interface HTMLDesktopHideElement extends Components.DesktopHide, HTMLStencilElement {
    }
    var HTMLDesktopHideElement: {
        prototype: HTMLDesktopHideElement;
        new (): HTMLDesktopHideElement;
    };
    interface HTMLElectionsCandidatesElement extends Components.ElectionsCandidates, HTMLStencilElement {
    }
    var HTMLElectionsCandidatesElement: {
        prototype: HTMLElectionsCandidatesElement;
        new (): HTMLElectionsCandidatesElement;
    };
    interface HTMLElectionsFooterElement extends Components.ElectionsFooter, HTMLStencilElement {
    }
    var HTMLElectionsFooterElement: {
        prototype: HTMLElectionsFooterElement;
        new (): HTMLElectionsFooterElement;
    };
    interface HTMLEventsCardsModalElement extends Components.EventsCardsModal, HTMLStencilElement {
    }
    var HTMLEventsCardsModalElement: {
        prototype: HTMLEventsCardsModalElement;
        new (): HTMLEventsCardsModalElement;
    };
    interface HTMLFlexContainerElement extends Components.FlexContainer, HTMLStencilElement {
    }
    var HTMLFlexContainerElement: {
        prototype: HTMLFlexContainerElement;
        new (): HTMLFlexContainerElement;
    };
    interface HTMLFullBioElement extends Components.FullBio, HTMLStencilElement {
    }
    var HTMLFullBioElement: {
        prototype: HTMLFullBioElement;
        new (): HTMLFullBioElement;
    };
    interface HTMLFullwidthBeigeStripElement extends Components.FullwidthBeigeStrip, HTMLStencilElement {
    }
    var HTMLFullwidthBeigeStripElement: {
        prototype: HTMLFullwidthBeigeStripElement;
        new (): HTMLFullwidthBeigeStripElement;
    };
    interface HTMLFullwidthStripElement extends Components.FullwidthStrip, HTMLStencilElement {
    }
    var HTMLFullwidthStripElement: {
        prototype: HTMLFullwidthStripElement;
        new (): HTMLFullwidthStripElement;
    };
    interface HTMLGalleryThumbnailElement extends Components.GalleryThumbnail, HTMLStencilElement {
    }
    var HTMLGalleryThumbnailElement: {
        prototype: HTMLGalleryThumbnailElement;
        new (): HTMLGalleryThumbnailElement;
    };
    interface HTMLGalleryThumbnailStackedElement extends Components.GalleryThumbnailStacked, HTMLStencilElement {
    }
    var HTMLGalleryThumbnailStackedElement: {
        prototype: HTMLGalleryThumbnailStackedElement;
        new (): HTMLGalleryThumbnailStackedElement;
    };
    interface HTMLGetInvolvedElement extends Components.GetInvolved, HTMLStencilElement {
    }
    var HTMLGetInvolvedElement: {
        prototype: HTMLGetInvolvedElement;
        new (): HTMLGetInvolvedElement;
    };
    interface HTMLGridLandingElement extends Components.GridLanding, HTMLStencilElement {
    }
    var HTMLGridLandingElement: {
        prototype: HTMLGridLandingElement;
        new (): HTMLGridLandingElement;
    };
    interface HTMLGridLandingItemElement extends Components.GridLandingItem, HTMLStencilElement {
    }
    var HTMLGridLandingItemElement: {
        prototype: HTMLGridLandingItemElement;
        new (): HTMLGridLandingItemElement;
    };
    interface HTMLImageFitContainerElement extends Components.ImageFitContainer, HTMLStencilElement {
    }
    var HTMLImageFitContainerElement: {
        prototype: HTMLImageFitContainerElement;
        new (): HTMLImageFitContainerElement;
    };
    interface HTMLImageSliderAutoElement extends Components.ImageSliderAuto, HTMLStencilElement {
    }
    var HTMLImageSliderAutoElement: {
        prototype: HTMLImageSliderAutoElement;
        new (): HTMLImageSliderAutoElement;
    };
    interface HTMLImageTextElement extends Components.ImageText, HTMLStencilElement {
    }
    var HTMLImageTextElement: {
        prototype: HTMLImageTextElement;
        new (): HTMLImageTextElement;
    };
    interface HTMLInnerTabContentElement extends Components.InnerTabContent, HTMLStencilElement {
    }
    var HTMLInnerTabContentElement: {
        prototype: HTMLInnerTabContentElement;
        new (): HTMLInnerTabContentElement;
    };
    interface HTMLInnerTabHeaderElement extends Components.InnerTabHeader, HTMLStencilElement {
    }
    var HTMLInnerTabHeaderElement: {
        prototype: HTMLInnerTabHeaderElement;
        new (): HTMLInnerTabHeaderElement;
    };
    interface HTMLInnerTabsContainerElement extends Components.InnerTabsContainer, HTMLStencilElement {
    }
    var HTMLInnerTabsContainerElement: {
        prototype: HTMLInnerTabsContainerElement;
        new (): HTMLInnerTabsContainerElement;
    };
    interface HTMLKclsuButtonElement extends Components.KclsuButton, HTMLStencilElement {
    }
    var HTMLKclsuButtonElement: {
        prototype: HTMLKclsuButtonElement;
        new (): HTMLKclsuButtonElement;
    };
    interface HTMLKclsuCountdownElement extends Components.KclsuCountdown, HTMLStencilElement {
    }
    var HTMLKclsuCountdownElement: {
        prototype: HTMLKclsuCountdownElement;
        new (): HTMLKclsuCountdownElement;
    };
    interface HTMLKclsuModalElement extends Components.KclsuModal, HTMLStencilElement {
    }
    var HTMLKclsuModalElement: {
        prototype: HTMLKclsuModalElement;
        new (): HTMLKclsuModalElement;
    };
    interface HTMLKclsuSearchElement extends Components.KclsuSearch, HTMLStencilElement {
    }
    var HTMLKclsuSearchElement: {
        prototype: HTMLKclsuSearchElement;
        new (): HTMLKclsuSearchElement;
    };
    interface HTMLKclsuTabsContainerElement extends Components.KclsuTabsContainer, HTMLStencilElement {
    }
    var HTMLKclsuTabsContainerElement: {
        prototype: HTMLKclsuTabsContainerElement;
        new (): HTMLKclsuTabsContainerElement;
    };
    interface HTMLLabelCardElement extends Components.LabelCard, HTMLStencilElement {
    }
    var HTMLLabelCardElement: {
        prototype: HTMLLabelCardElement;
        new (): HTMLLabelCardElement;
    };
    interface HTMLLastYearScoresElement extends Components.LastYearScores, HTMLStencilElement {
    }
    var HTMLLastYearScoresElement: {
        prototype: HTMLLastYearScoresElement;
        new (): HTMLLastYearScoresElement;
    };
    interface HTMLLazyImageElement extends Components.LazyImage, HTMLStencilElement {
    }
    var HTMLLazyImageElement: {
        prototype: HTMLLazyImageElement;
        new (): HTMLLazyImageElement;
    };
    interface HTMLLoadingSpinnerElement extends Components.LoadingSpinner, HTMLStencilElement {
    }
    var HTMLLoadingSpinnerElement: {
        prototype: HTMLLoadingSpinnerElement;
        new (): HTMLLoadingSpinnerElement;
    };
    interface HTMLMobileHideElement extends Components.MobileHide, HTMLStencilElement {
    }
    var HTMLMobileHideElement: {
        prototype: HTMLMobileHideElement;
        new (): HTMLMobileHideElement;
    };
    interface HTMLModalBackdropElement extends Components.ModalBackdrop, HTMLStencilElement {
    }
    var HTMLModalBackdropElement: {
        prototype: HTMLModalBackdropElement;
        new (): HTMLModalBackdropElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLNewsCardElement extends Components.NewsCard, HTMLStencilElement {
    }
    var HTMLNewsCardElement: {
        prototype: HTMLNewsCardElement;
        new (): HTMLNewsCardElement;
    };
    interface HTMLPageContentElement extends Components.PageContent, HTMLStencilElement {
    }
    var HTMLPageContentElement: {
        prototype: HTMLPageContentElement;
        new (): HTMLPageContentElement;
    };
    interface HTMLPresetCardElement extends Components.PresetCard, HTMLStencilElement {
    }
    var HTMLPresetCardElement: {
        prototype: HTMLPresetCardElement;
        new (): HTMLPresetCardElement;
    };
    interface HTMLPresetControlsElement extends Components.PresetControls, HTMLStencilElement {
    }
    var HTMLPresetControlsElement: {
        prototype: HTMLPresetControlsElement;
        new (): HTMLPresetControlsElement;
    };
    interface HTMLPrimaryButtonElement extends Components.PrimaryButton, HTMLStencilElement {
    }
    var HTMLPrimaryButtonElement: {
        prototype: HTMLPrimaryButtonElement;
        new (): HTMLPrimaryButtonElement;
    };
    interface HTMLProfileCardElement extends Components.ProfileCard, HTMLStencilElement {
    }
    var HTMLProfileCardElement: {
        prototype: HTMLProfileCardElement;
        new (): HTMLProfileCardElement;
    };
    interface HTMLProfileCardLayoutElement extends Components.ProfileCardLayout, HTMLStencilElement {
    }
    var HTMLProfileCardLayoutElement: {
        prototype: HTMLProfileCardLayoutElement;
        new (): HTMLProfileCardLayoutElement;
    };
    interface HTMLProfileLogoCardElement extends Components.ProfileLogoCard, HTMLStencilElement {
    }
    var HTMLProfileLogoCardElement: {
        prototype: HTMLProfileLogoCardElement;
        new (): HTMLProfileLogoCardElement;
    };
    interface HTMLProfileTabsElement extends Components.ProfileTabs, HTMLStencilElement {
    }
    var HTMLProfileTabsElement: {
        prototype: HTMLProfileTabsElement;
        new (): HTMLProfileTabsElement;
    };
    interface HTMLPurpleButtonElement extends Components.PurpleButton, HTMLStencilElement {
    }
    var HTMLPurpleButtonElement: {
        prototype: HTMLPurpleButtonElement;
        new (): HTMLPurpleButtonElement;
    };
    interface HTMLQuickLinkElement extends Components.QuickLink, HTMLStencilElement {
    }
    var HTMLQuickLinkElement: {
        prototype: HTMLQuickLinkElement;
        new (): HTMLQuickLinkElement;
    };
    interface HTMLQuickLinksElement extends Components.QuickLinks, HTMLStencilElement {
    }
    var HTMLQuickLinksElement: {
        prototype: HTMLQuickLinksElement;
        new (): HTMLQuickLinksElement;
    };
    interface HTMLShowSupportElement extends Components.ShowSupport, HTMLStencilElement {
    }
    var HTMLShowSupportElement: {
        prototype: HTMLShowSupportElement;
        new (): HTMLShowSupportElement;
    };
    interface HTMLSupportOptionElement extends Components.SupportOption, HTMLStencilElement {
    }
    var HTMLSupportOptionElement: {
        prototype: HTMLSupportOptionElement;
        new (): HTMLSupportOptionElement;
    };
    interface HTMLSupportProgressElement extends Components.SupportProgress, HTMLStencilElement {
    }
    var HTMLSupportProgressElement: {
        prototype: HTMLSupportProgressElement;
        new (): HTMLSupportProgressElement;
    };
    interface HTMLTabContentElement extends Components.TabContent, HTMLStencilElement {
    }
    var HTMLTabContentElement: {
        prototype: HTMLTabContentElement;
        new (): HTMLTabContentElement;
    };
    interface HTMLTabHeaderElement extends Components.TabHeader, HTMLStencilElement {
    }
    var HTMLTabHeaderElement: {
        prototype: HTMLTabHeaderElement;
        new (): HTMLTabHeaderElement;
    };
    interface HTMLTabsContainerElement extends Components.TabsContainer, HTMLStencilElement {
    }
    var HTMLTabsContainerElement: {
        prototype: HTMLTabsContainerElement;
        new (): HTMLTabsContainerElement;
    };
    interface HTMLTextCardElement extends Components.TextCard, HTMLStencilElement {
    }
    var HTMLTextCardElement: {
        prototype: HTMLTextCardElement;
        new (): HTMLTextCardElement;
    };
    interface HTMLUserLoginElement extends Components.UserLogin, HTMLStencilElement {
    }
    var HTMLUserLoginElement: {
        prototype: HTMLUserLoginElement;
        new (): HTMLUserLoginElement;
    };
    interface HTMLVarsityLandingElement extends Components.VarsityLanding, HTMLStencilElement {
    }
    var HTMLVarsityLandingElement: {
        prototype: HTMLVarsityLandingElement;
        new (): HTMLVarsityLandingElement;
    };
    interface HTMLVarsityNextMatchesElement extends Components.VarsityNextMatches, HTMLStencilElement {
    }
    var HTMLVarsityNextMatchesElement: {
        prototype: HTMLVarsityNextMatchesElement;
        new (): HTMLVarsityNextMatchesElement;
    };
    interface HTMLVarsityRaceElement extends Components.VarsityRace, HTMLStencilElement {
    }
    var HTMLVarsityRaceElement: {
        prototype: HTMLVarsityRaceElement;
        new (): HTMLVarsityRaceElement;
    };
    interface HTMLVarsityTotalScoreElement extends Components.VarsityTotalScore, HTMLStencilElement {
    }
    var HTMLVarsityTotalScoreElement: {
        prototype: HTMLVarsityTotalScoreElement;
        new (): HTMLVarsityTotalScoreElement;
    };
    interface HTMLVarsityUpcomingElement extends Components.VarsityUpcoming, HTMLStencilElement {
    }
    var HTMLVarsityUpcomingElement: {
        prototype: HTMLVarsityUpcomingElement;
        new (): HTMLVarsityUpcomingElement;
    };
    interface HTMLVarsityWeatherElement extends Components.VarsityWeather, HTMLStencilElement {
    }
    var HTMLVarsityWeatherElement: {
        prototype: HTMLVarsityWeatherElement;
        new (): HTMLVarsityWeatherElement;
    };
    interface HTMLVideoBannerElement extends Components.VideoBanner, HTMLStencilElement {
    }
    var HTMLVideoBannerElement: {
        prototype: HTMLVideoBannerElement;
        new (): HTMLVideoBannerElement;
    };
    interface HTMLVideoEmbedElement extends Components.VideoEmbed, HTMLStencilElement {
    }
    var HTMLVideoEmbedElement: {
        prototype: HTMLVideoEmbedElement;
        new (): HTMLVideoEmbedElement;
    };
    interface HTMLVideoGalleryElement extends Components.VideoGallery, HTMLStencilElement {
    }
    var HTMLVideoGalleryElement: {
        prototype: HTMLVideoGalleryElement;
        new (): HTMLVideoGalleryElement;
    };
    interface HTMLVideoGalleryStackedElement extends Components.VideoGalleryStacked, HTMLStencilElement {
    }
    var HTMLVideoGalleryStackedElement: {
        prototype: HTMLVideoGalleryStackedElement;
        new (): HTMLVideoGalleryStackedElement;
    };
    interface HTMLElementTagNameMap {
        "academic-candidate-display": HTMLAcademicCandidateDisplayElement;
        "accordion-container": HTMLAccordionContainerElement;
        "accordion-dropdown": HTMLAccordionDropdownElement;
        "add-varsity-scores": HTMLAddVarsityScoresElement;
        "campaign-aim": HTMLCampaignAimElement;
        "campaign-aim-container": HTMLCampaignAimContainerElement;
        "campaign-news": HTMLCampaignNewsElement;
        "campaign-page": HTMLCampaignPageElement;
        "campaign-tabs": HTMLCampaignTabsElement;
        "candidate-display": HTMLCandidateDisplayElement;
        "candidate-upload": HTMLCandidateUploadElement;
        "cloudinary-app": HTMLCloudinaryAppElement;
        "create-varsity-data": HTMLCreateVarsityDataElement;
        "desktop-hide": HTMLDesktopHideElement;
        "elections-candidates": HTMLElectionsCandidatesElement;
        "elections-footer": HTMLElectionsFooterElement;
        "events-cards-modal": HTMLEventsCardsModalElement;
        "flex-container": HTMLFlexContainerElement;
        "full-bio": HTMLFullBioElement;
        "fullwidth-beige-strip": HTMLFullwidthBeigeStripElement;
        "fullwidth-strip": HTMLFullwidthStripElement;
        "gallery-thumbnail": HTMLGalleryThumbnailElement;
        "gallery-thumbnail-stacked": HTMLGalleryThumbnailStackedElement;
        "get-involved": HTMLGetInvolvedElement;
        "grid-landing": HTMLGridLandingElement;
        "grid-landing-item": HTMLGridLandingItemElement;
        "image-fit-container": HTMLImageFitContainerElement;
        "image-slider-auto": HTMLImageSliderAutoElement;
        "image-text": HTMLImageTextElement;
        "inner-tab-content": HTMLInnerTabContentElement;
        "inner-tab-header": HTMLInnerTabHeaderElement;
        "inner-tabs-container": HTMLInnerTabsContainerElement;
        "kclsu-button": HTMLKclsuButtonElement;
        "kclsu-countdown": HTMLKclsuCountdownElement;
        "kclsu-modal": HTMLKclsuModalElement;
        "kclsu-search": HTMLKclsuSearchElement;
        "kclsu-tabs-container": HTMLKclsuTabsContainerElement;
        "label-card": HTMLLabelCardElement;
        "last-year-scores": HTMLLastYearScoresElement;
        "lazy-image": HTMLLazyImageElement;
        "loading-spinner": HTMLLoadingSpinnerElement;
        "mobile-hide": HTMLMobileHideElement;
        "modal-backdrop": HTMLModalBackdropElement;
        "my-component": HTMLMyComponentElement;
        "news-card": HTMLNewsCardElement;
        "page-content": HTMLPageContentElement;
        "preset-card": HTMLPresetCardElement;
        "preset-controls": HTMLPresetControlsElement;
        "primary-button": HTMLPrimaryButtonElement;
        "profile-card": HTMLProfileCardElement;
        "profile-card-layout": HTMLProfileCardLayoutElement;
        "profile-logo-card": HTMLProfileLogoCardElement;
        "profile-tabs": HTMLProfileTabsElement;
        "purple-button": HTMLPurpleButtonElement;
        "quick-link": HTMLQuickLinkElement;
        "quick-links": HTMLQuickLinksElement;
        "show-support": HTMLShowSupportElement;
        "support-option": HTMLSupportOptionElement;
        "support-progress": HTMLSupportProgressElement;
        "tab-content": HTMLTabContentElement;
        "tab-header": HTMLTabHeaderElement;
        "tabs-container": HTMLTabsContainerElement;
        "text-card": HTMLTextCardElement;
        "user-login": HTMLUserLoginElement;
        "varsity-landing": HTMLVarsityLandingElement;
        "varsity-next-matches": HTMLVarsityNextMatchesElement;
        "varsity-race": HTMLVarsityRaceElement;
        "varsity-total-score": HTMLVarsityTotalScoreElement;
        "varsity-upcoming": HTMLVarsityUpcomingElement;
        "varsity-weather": HTMLVarsityWeatherElement;
        "video-banner": HTMLVideoBannerElement;
        "video-embed": HTMLVideoEmbedElement;
        "video-gallery": HTMLVideoGalleryElement;
        "video-gallery-stacked": HTMLVideoGalleryStackedElement;
    }
}
declare namespace LocalJSX {
    interface AcademicCandidateDisplay {
        "data"?: any;
    }
    interface AccordionContainer {
    }
    interface AccordionDropdown {
        "header"?: string;
    }
    interface AddVarsityScores {
        "year"?: string;
    }
    interface CampaignAim {
    }
    interface CampaignAimContainer {
        "campaignname"?: string;
    }
    interface CampaignNews {
        "newsid"?: string;
    }
    interface CampaignPage {
        "campaignId"?: number;
        "name"?: string;
    }
    interface CampaignTabs {
        "facebook"?: string;
        "newsid"?: string;
        "socials"?: string;
        "strategydoc"?: string;
    }
    interface CandidateDisplay {
        "data"?: any;
    }
    interface CandidateUpload {
        /**
          * MSL ELections ID
         */
        "electionid"?: string;
        /**
          * The JSON generated from the browser-side uploaded excel spreadsheet
         */
        "spreadsheetdata"?: any;
        /**
          * Either 'candidates' or 'results'. Will set the firebase url and key map
         */
        "stage"?: string;
    }
    interface CloudinaryApp {
        "public_id"?: string;
    }
    interface CreateVarsityData {
        "allowcreate"?: boolean;
        "allowupdate"?: boolean;
        "msltag"?: string;
        "test"?: boolean;
        "year"?: string;
    }
    interface DesktopHide {
        /**
          * In addition to hiding all children content in screens desktop + bigger, this will hide content in screens tablet + bigger
         */
        "hidetablet"?: boolean;
    }
    interface ElectionsCandidates {
        /**
          * A string lof either Faculties or Association search terms, separated by the | sign. PLEASE NOTE: The name will be used to filter all roles, as well as be used for the Tab Header title
         */
        "academicgroups"?: any;
        /**
          * The primary acrtive tab that will be open on page load
         */
        "activeid"?: string;
        /**
          * The election ID from MSL!
         */
        "electionid"?: string;
        /**
          * A string of exact role names for network officers, separated by the | sign
         */
        "networkofficers"?: any;
        /**
          * Set to true to display results data. False to display All Candidates
         */
        "results"?: boolean;
        /**
          * A string of exact role names for student officers, separated by the | sign
         */
        "studentofficers"?: any;
    }
    interface ElectionsFooter {
    }
    interface EventsCardsModal {
    }
    interface FlexContainer {
        /**
          * The same as the 'justify-content' flex property along the x axis
         */
        "alignx"?: string;
        /**
          * The same as the 'align-items' flex property along the y axis
         */
        "aligny"?: string;
        /**
          * Set the flex direction: column, reverse-column, row, reverse-row
         */
        "direction"?: string;
        /**
          * Ensure the container stretches the full width and height of parent container
         */
        "fillcontainer"?: boolean;
        /**
          * In mobile display in column direction - NOT YET RELEASED
         */
        "mobcolumn"?: boolean;
        /**
          * If the parent container element needs to be an <ul> list element
         */
        "renderlist"?: boolean;
        /**
          * Add flex-wrap to flex items
         */
        "wrap"?: boolean;
    }
    interface FullBio {
        "data"?: any;
    }
    interface FullwidthBeigeStrip {
    }
    interface FullwidthStrip {
        "color"?: string;
        "height"?: string;
    }
    interface GalleryThumbnail {
        "active"?: boolean;
        "cardheight"?: string;
        "emitid"?: string;
        "image"?: string;
        "onEmitClick"?: (event: CustomEvent<any>) => void;
        "videotitle"?: string;
    }
    interface GalleryThumbnailStacked {
        "active"?: boolean;
        "cardheight"?: string;
        "emitid"?: string;
        "image"?: string;
        "onEmitClick"?: (event: CustomEvent<any>) => void;
        "videotitle"?: string;
    }
    interface GetInvolved {
        "typeform"?: string;
    }
    interface GridLanding {
    }
    interface GridLandingItem {
        "height"?: string;
        "label"?: string;
        "width"?: string;
    }
    interface ImageFitContainer {
        "alt"?: string;
        "classes"?: string;
        "src"?: string;
    }
    interface ImageSliderAuto {
        "classes"?: string;
        /**
          * A string of images
         */
        "images"?: string[];
        "interval"?: number;
    }
    interface ImageText {
        /**
          * The title at the top of the text
         */
        "heading"?: string;
        /**
          * The image link (get from Cloudinary)
         */
        "image"?: string;
        /**
          * Animate the image (scale in) on scroll
         */
        "imagezoom"?: boolean;
        /**
          * Set the margin for the card
         */
        "margin"?: string;
        /**
          * Applies to MOBILE / TABLET <780px screens only. Paragraph and heading sizes reduced
         */
        "smalltext"?: boolean;
        /**
          * Switch the side the image is on
         */
        "switch"?: boolean;
        /**
          * The paragraph text
         */
        "text"?: string;
        /**
          * Choose the colour for the paragraph text
         */
        "textcolour"?: string;
    }
    interface InnerTabContent {
        "active"?: boolean;
        "name"?: string;
    }
    interface InnerTabHeader {
        "active"?: boolean;
        "name"?: string;
        "onSelectInnerTab"?: (event: CustomEvent<any>) => void;
    }
    interface InnerTabsContainer {
        "innertab"?: boolean;
    }
    interface KclsuButton {
        /**
          * Centers the button in the page
         */
        "center"?: boolean;
        /**
          * Makes the link download
         */
        "download"?: boolean;
        /**
          * Event Listener name
         */
        "emitid"?: string;
        /**
          * Give the button a fixed width
         */
        "fixedwidth"?: string;
        /**
          * Adds icon to the page
         */
        "icon"?: string;
        /**
          * The URL to link to
         */
        "link"?: string;
        /**
          * specifiy a margin, otherwise uses default
         */
        "margin"?: string;
        /**
          * Opens the link in a new tab
         */
        "newtab"?: boolean;
        "onEmitClick"?: (event: CustomEvent<any>) => void;
        /**
          * Make the button a secondary purple button
         */
        "purple"?: boolean;
        /**
          * Give the button rounded corners
         */
        "rounded"?: boolean;
        /**
          * Make the button small
         */
        "small"?: boolean;
        /**
          * The text for the button
         */
        "text"?: string;
        /**
          * Makes the button very small
         */
        "verysmall"?: boolean;
    }
    interface KclsuCountdown {
        /**
          * The date to countdown to. Must match date string format
         */
        "date": string;
        /**
          * Optional: set a fixed font-size for tablet, desktop and wider.
         */
        "fontsize"?: any;
        /**
          * The text beneath the countdown
         */
        "text"?: any;
        /**
          * Optional: set a colour for the text beneath the countdown.
         */
        "textcolour"?: any;
    }
    interface KclsuModal {
        /**
          * This will allow a user to click away and hide the modal when open
         */
        "autoexit"?: boolean;
        /**
          * Set position to absolute or other. Defaults to fixed
         */
        "position"?: string;
        /**
          * Controls when the modal is open and visible or not
         */
        "show"?: boolean;
    }
    interface KclsuSearch {
        /**
          * If searching an custom web component, provide the name of the atrribute to query
         */
        "attr"?: string;
        /**
          * The container of the search result / search field, used to hide the element from results. Can be a tag, class or id
         */
        "containerselector": string;
        /**
          * The text inside the search input, which disappears once a user starts typing
         */
        "placeholdertext"?: string;
        /**
          * If searching an HTML element, provide the element's selector - tag, class or id
         */
        "selector"?: string;
    }
    interface KclsuTabsContainer {
    }
    interface LabelCard {
        /**
          * If a button included, the link for the button
         */
        "buttonlink"?: string;
        /**
          * If a button included, the text for the button
         */
        "buttontitle"?: string;
        "cardheight"?: string;
        /**
          * The main title of the card
         */
        "cardtitle"?: string;
        /**
          * The main title of the card
         */
        "highlightText"?: boolean;
        "image"?: string;
        /**
          * The link for the card - NOT for the button
         */
        "link"?: string;
        /**
          * If image to be displayed on right hand side
         */
        "reverse"?: boolean;
        "smallestheight"?: boolean;
        "smallheading"?: boolean;
        /**
          * The sub text beneath the title
         */
        "text"?: string;
    }
    interface LastYearScores {
    }
    interface LazyImage {
        /**
          * Image will scale into view
         */
        "animatein"?: boolean;
        /**
          * If setting width for mobile and desktop, use width property for mobile and this property for desktop
         */
        "desktopwidth"?: string;
        /**
          * Use standard CSS values to set a focus area on the image. EG 'center left'
         */
        "focusarea"?: string;
        "image"?: string;
        /**
          * A width for the image in pixels
         */
        "width"?: string;
    }
    interface LoadingSpinner {
        "show"?: boolean;
    }
    interface MobileHide {
        /**
          * In addition to hiding all children in screens mobile + smaller, this will hide content in screens tablet + smaller
         */
        "hidetablet"?: boolean;
    }
    interface ModalBackdrop {
        "onExitModal"?: (event: CustomEvent<any>) => void;
        "showbg"?: boolean;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface NewsCard {
        "newslink"?: string;
        "newstitle"?: string;
    }
    interface PageContent {
    }
    interface PresetCard {
        "dimensions"?: string;
        "onSelectPreset"?: (event: CustomEvent<any>) => void;
        "presetid"?: string;
        "presetname"?: string;
    }
    interface PresetControls {
        "onSubmitEdits"?: (event: CustomEvent<any>) => void;
    }
    interface PrimaryButton {
        "to"?: string;
    }
    interface ProfileCard {
        /**
          * The text for the primary text link bottom left
         */
        "cta"?: string;
        /**
          * The ID string for click events. Only applies to card's bottom right link- DEVELOPER USE
         */
        "emitid"?: string;
        /**
          * The image URL
         */
        "image"?: string;
        /**
          * The URL link for the primary text link on the bottom left of the card
         */
        "link"?: string;
        /**
          * The title for the card - usually a full name
         */
        "name"?: string;
        "onEmitClick"?: (event: CustomEvent<any>) => void;
        /**
          * A sub heading - usually a position or field title
         */
        "position"?: string;
        /**
          * The text for the secondary text link bottom right
         */
        "secondcta"?: string;
        /**
          * A second URL link for the bottom right of the card
         */
        "secondlink"?: string;
    }
    interface ProfileCardLayout {
    }
    interface ProfileLogoCard {
        /**
          * The text title of the card
         */
        "cardtitle": string;
        /**
          * The background image URL
         */
        "image"?: string;
        /**
          * Specify which part of the image you want to focus - top, bottom, right, left, center
         */
        "imagefocus"?: string;
        /**
          * The URL link for the the card
         */
        "link"?: string;
        /**
          * The logo image URL 150x150px
         */
        "logo"?: string;
        /**
          * OPTIONAL - if you are using a transparent text icon and need to set a background colour
         */
        "logocolour"?: string;
    }
    interface ProfileTabs {
        /**
          * Specify Tab ID you want to keep open by default
         */
        "activeid"?: string;
        /**
          * The URL of the database to fetch profiles from (firebase)
         */
        "database"?: string;
        /**
          * Array with child arrays containing Tab Heading, Tab ID, and Text(optional)
         */
        "headings"?: any;
    }
    interface PurpleButton {
        "link"?: string;
        "whitetext"?: boolean;
    }
    interface QuickLink {
        "to"?: string;
    }
    interface QuickLinks {
        "name"?: string;
    }
    interface ShowSupport {
    }
    interface SupportOption {
        "heading"?: string;
        "supportname"?: string;
    }
    interface SupportProgress {
        "current"?: any;
        "maxtotal"?: any;
        "supportname"?: string;
    }
    interface TabContent {
        "active"?: boolean;
        "name"?: string;
    }
    interface TabHeader {
        "active"?: boolean;
        "index"?: string;
        "name"?: string;
        "onSelectTab"?: (event: CustomEvent<any>) => void;
        "onSelectTabByIndex"?: (event: CustomEvent<any>) => void;
    }
    interface TabsContainer {
        "innertab"?: boolean;
    }
    interface TextCard {
        /**
          * The purple heading in the card
         */
        "cardtitle": string;
        /**
          * The Url link you want to link to
         */
        "link"?: string;
        /**
          * Any extra text. If you want it to be empty, add empty string value:  ""
         */
        "subtext"?: string;
    }
    interface UserLogin {
        /**
          * The name of the database area. For example: projectx
         */
        "database"?: string;
    }
    interface VarsityLanding {
        "currentDate"?: {
            weekday: string;
            day: any;
            month: string;
            year: any;
            hours: any;
            minutes: any;
        };
        "year"?: string;
    }
    interface VarsityNextMatches {
        "data"?: any;
    }
    interface VarsityRace {
        "data"?: any;
        "target"?: number;
    }
    interface VarsityTotalScore {
        "scores"?: any;
    }
    interface VarsityUpcoming {
        "data"?: any;
        "showall"?: boolean;
    }
    interface VarsityWeather {
    }
    interface VideoBanner {
        "url"?: string;
    }
    interface VideoEmbed {
        /**
          * The id of the Youtube Video - found in the URL eg youtube.com/watch?v={VIDEO_ID}
         */
        "embedid"?: any;
        /**
          * The URL of the Youtube video you want to display - CURRENTLY NOT WORKING
         */
        "url"?: string;
    }
    interface VideoGallery {
        /**
          * The Youtube URL for any given playlist
         */
        "playlist": any;
    }
    interface VideoGalleryStacked {
        /**
          * The Youtube URL for any given playlist
         */
        "playlist": any;
    }
    interface IntrinsicElements {
        "academic-candidate-display": AcademicCandidateDisplay;
        "accordion-container": AccordionContainer;
        "accordion-dropdown": AccordionDropdown;
        "add-varsity-scores": AddVarsityScores;
        "campaign-aim": CampaignAim;
        "campaign-aim-container": CampaignAimContainer;
        "campaign-news": CampaignNews;
        "campaign-page": CampaignPage;
        "campaign-tabs": CampaignTabs;
        "candidate-display": CandidateDisplay;
        "candidate-upload": CandidateUpload;
        "cloudinary-app": CloudinaryApp;
        "create-varsity-data": CreateVarsityData;
        "desktop-hide": DesktopHide;
        "elections-candidates": ElectionsCandidates;
        "elections-footer": ElectionsFooter;
        "events-cards-modal": EventsCardsModal;
        "flex-container": FlexContainer;
        "full-bio": FullBio;
        "fullwidth-beige-strip": FullwidthBeigeStrip;
        "fullwidth-strip": FullwidthStrip;
        "gallery-thumbnail": GalleryThumbnail;
        "gallery-thumbnail-stacked": GalleryThumbnailStacked;
        "get-involved": GetInvolved;
        "grid-landing": GridLanding;
        "grid-landing-item": GridLandingItem;
        "image-fit-container": ImageFitContainer;
        "image-slider-auto": ImageSliderAuto;
        "image-text": ImageText;
        "inner-tab-content": InnerTabContent;
        "inner-tab-header": InnerTabHeader;
        "inner-tabs-container": InnerTabsContainer;
        "kclsu-button": KclsuButton;
        "kclsu-countdown": KclsuCountdown;
        "kclsu-modal": KclsuModal;
        "kclsu-search": KclsuSearch;
        "kclsu-tabs-container": KclsuTabsContainer;
        "label-card": LabelCard;
        "last-year-scores": LastYearScores;
        "lazy-image": LazyImage;
        "loading-spinner": LoadingSpinner;
        "mobile-hide": MobileHide;
        "modal-backdrop": ModalBackdrop;
        "my-component": MyComponent;
        "news-card": NewsCard;
        "page-content": PageContent;
        "preset-card": PresetCard;
        "preset-controls": PresetControls;
        "primary-button": PrimaryButton;
        "profile-card": ProfileCard;
        "profile-card-layout": ProfileCardLayout;
        "profile-logo-card": ProfileLogoCard;
        "profile-tabs": ProfileTabs;
        "purple-button": PurpleButton;
        "quick-link": QuickLink;
        "quick-links": QuickLinks;
        "show-support": ShowSupport;
        "support-option": SupportOption;
        "support-progress": SupportProgress;
        "tab-content": TabContent;
        "tab-header": TabHeader;
        "tabs-container": TabsContainer;
        "text-card": TextCard;
        "user-login": UserLogin;
        "varsity-landing": VarsityLanding;
        "varsity-next-matches": VarsityNextMatches;
        "varsity-race": VarsityRace;
        "varsity-total-score": VarsityTotalScore;
        "varsity-upcoming": VarsityUpcoming;
        "varsity-weather": VarsityWeather;
        "video-banner": VideoBanner;
        "video-embed": VideoEmbed;
        "video-gallery": VideoGallery;
        "video-gallery-stacked": VideoGalleryStacked;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "academic-candidate-display": LocalJSX.AcademicCandidateDisplay & JSXBase.HTMLAttributes<HTMLAcademicCandidateDisplayElement>;
            "accordion-container": LocalJSX.AccordionContainer & JSXBase.HTMLAttributes<HTMLAccordionContainerElement>;
            "accordion-dropdown": LocalJSX.AccordionDropdown & JSXBase.HTMLAttributes<HTMLAccordionDropdownElement>;
            "add-varsity-scores": LocalJSX.AddVarsityScores & JSXBase.HTMLAttributes<HTMLAddVarsityScoresElement>;
            "campaign-aim": LocalJSX.CampaignAim & JSXBase.HTMLAttributes<HTMLCampaignAimElement>;
            "campaign-aim-container": LocalJSX.CampaignAimContainer & JSXBase.HTMLAttributes<HTMLCampaignAimContainerElement>;
            "campaign-news": LocalJSX.CampaignNews & JSXBase.HTMLAttributes<HTMLCampaignNewsElement>;
            "campaign-page": LocalJSX.CampaignPage & JSXBase.HTMLAttributes<HTMLCampaignPageElement>;
            "campaign-tabs": LocalJSX.CampaignTabs & JSXBase.HTMLAttributes<HTMLCampaignTabsElement>;
            "candidate-display": LocalJSX.CandidateDisplay & JSXBase.HTMLAttributes<HTMLCandidateDisplayElement>;
            "candidate-upload": LocalJSX.CandidateUpload & JSXBase.HTMLAttributes<HTMLCandidateUploadElement>;
            "cloudinary-app": LocalJSX.CloudinaryApp & JSXBase.HTMLAttributes<HTMLCloudinaryAppElement>;
            "create-varsity-data": LocalJSX.CreateVarsityData & JSXBase.HTMLAttributes<HTMLCreateVarsityDataElement>;
            "desktop-hide": LocalJSX.DesktopHide & JSXBase.HTMLAttributes<HTMLDesktopHideElement>;
            "elections-candidates": LocalJSX.ElectionsCandidates & JSXBase.HTMLAttributes<HTMLElectionsCandidatesElement>;
            "elections-footer": LocalJSX.ElectionsFooter & JSXBase.HTMLAttributes<HTMLElectionsFooterElement>;
            "events-cards-modal": LocalJSX.EventsCardsModal & JSXBase.HTMLAttributes<HTMLEventsCardsModalElement>;
            "flex-container": LocalJSX.FlexContainer & JSXBase.HTMLAttributes<HTMLFlexContainerElement>;
            "full-bio": LocalJSX.FullBio & JSXBase.HTMLAttributes<HTMLFullBioElement>;
            "fullwidth-beige-strip": LocalJSX.FullwidthBeigeStrip & JSXBase.HTMLAttributes<HTMLFullwidthBeigeStripElement>;
            "fullwidth-strip": LocalJSX.FullwidthStrip & JSXBase.HTMLAttributes<HTMLFullwidthStripElement>;
            "gallery-thumbnail": LocalJSX.GalleryThumbnail & JSXBase.HTMLAttributes<HTMLGalleryThumbnailElement>;
            "gallery-thumbnail-stacked": LocalJSX.GalleryThumbnailStacked & JSXBase.HTMLAttributes<HTMLGalleryThumbnailStackedElement>;
            "get-involved": LocalJSX.GetInvolved & JSXBase.HTMLAttributes<HTMLGetInvolvedElement>;
            "grid-landing": LocalJSX.GridLanding & JSXBase.HTMLAttributes<HTMLGridLandingElement>;
            "grid-landing-item": LocalJSX.GridLandingItem & JSXBase.HTMLAttributes<HTMLGridLandingItemElement>;
            "image-fit-container": LocalJSX.ImageFitContainer & JSXBase.HTMLAttributes<HTMLImageFitContainerElement>;
            "image-slider-auto": LocalJSX.ImageSliderAuto & JSXBase.HTMLAttributes<HTMLImageSliderAutoElement>;
            "image-text": LocalJSX.ImageText & JSXBase.HTMLAttributes<HTMLImageTextElement>;
            "inner-tab-content": LocalJSX.InnerTabContent & JSXBase.HTMLAttributes<HTMLInnerTabContentElement>;
            "inner-tab-header": LocalJSX.InnerTabHeader & JSXBase.HTMLAttributes<HTMLInnerTabHeaderElement>;
            "inner-tabs-container": LocalJSX.InnerTabsContainer & JSXBase.HTMLAttributes<HTMLInnerTabsContainerElement>;
            "kclsu-button": LocalJSX.KclsuButton & JSXBase.HTMLAttributes<HTMLKclsuButtonElement>;
            "kclsu-countdown": LocalJSX.KclsuCountdown & JSXBase.HTMLAttributes<HTMLKclsuCountdownElement>;
            "kclsu-modal": LocalJSX.KclsuModal & JSXBase.HTMLAttributes<HTMLKclsuModalElement>;
            "kclsu-search": LocalJSX.KclsuSearch & JSXBase.HTMLAttributes<HTMLKclsuSearchElement>;
            "kclsu-tabs-container": LocalJSX.KclsuTabsContainer & JSXBase.HTMLAttributes<HTMLKclsuTabsContainerElement>;
            "label-card": LocalJSX.LabelCard & JSXBase.HTMLAttributes<HTMLLabelCardElement>;
            "last-year-scores": LocalJSX.LastYearScores & JSXBase.HTMLAttributes<HTMLLastYearScoresElement>;
            "lazy-image": LocalJSX.LazyImage & JSXBase.HTMLAttributes<HTMLLazyImageElement>;
            "loading-spinner": LocalJSX.LoadingSpinner & JSXBase.HTMLAttributes<HTMLLoadingSpinnerElement>;
            "mobile-hide": LocalJSX.MobileHide & JSXBase.HTMLAttributes<HTMLMobileHideElement>;
            "modal-backdrop": LocalJSX.ModalBackdrop & JSXBase.HTMLAttributes<HTMLModalBackdropElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "news-card": LocalJSX.NewsCard & JSXBase.HTMLAttributes<HTMLNewsCardElement>;
            "page-content": LocalJSX.PageContent & JSXBase.HTMLAttributes<HTMLPageContentElement>;
            "preset-card": LocalJSX.PresetCard & JSXBase.HTMLAttributes<HTMLPresetCardElement>;
            "preset-controls": LocalJSX.PresetControls & JSXBase.HTMLAttributes<HTMLPresetControlsElement>;
            "primary-button": LocalJSX.PrimaryButton & JSXBase.HTMLAttributes<HTMLPrimaryButtonElement>;
            "profile-card": LocalJSX.ProfileCard & JSXBase.HTMLAttributes<HTMLProfileCardElement>;
            "profile-card-layout": LocalJSX.ProfileCardLayout & JSXBase.HTMLAttributes<HTMLProfileCardLayoutElement>;
            "profile-logo-card": LocalJSX.ProfileLogoCard & JSXBase.HTMLAttributes<HTMLProfileLogoCardElement>;
            "profile-tabs": LocalJSX.ProfileTabs & JSXBase.HTMLAttributes<HTMLProfileTabsElement>;
            "purple-button": LocalJSX.PurpleButton & JSXBase.HTMLAttributes<HTMLPurpleButtonElement>;
            "quick-link": LocalJSX.QuickLink & JSXBase.HTMLAttributes<HTMLQuickLinkElement>;
            "quick-links": LocalJSX.QuickLinks & JSXBase.HTMLAttributes<HTMLQuickLinksElement>;
            "show-support": LocalJSX.ShowSupport & JSXBase.HTMLAttributes<HTMLShowSupportElement>;
            "support-option": LocalJSX.SupportOption & JSXBase.HTMLAttributes<HTMLSupportOptionElement>;
            "support-progress": LocalJSX.SupportProgress & JSXBase.HTMLAttributes<HTMLSupportProgressElement>;
            "tab-content": LocalJSX.TabContent & JSXBase.HTMLAttributes<HTMLTabContentElement>;
            "tab-header": LocalJSX.TabHeader & JSXBase.HTMLAttributes<HTMLTabHeaderElement>;
            "tabs-container": LocalJSX.TabsContainer & JSXBase.HTMLAttributes<HTMLTabsContainerElement>;
            "text-card": LocalJSX.TextCard & JSXBase.HTMLAttributes<HTMLTextCardElement>;
            "user-login": LocalJSX.UserLogin & JSXBase.HTMLAttributes<HTMLUserLoginElement>;
            "varsity-landing": LocalJSX.VarsityLanding & JSXBase.HTMLAttributes<HTMLVarsityLandingElement>;
            "varsity-next-matches": LocalJSX.VarsityNextMatches & JSXBase.HTMLAttributes<HTMLVarsityNextMatchesElement>;
            "varsity-race": LocalJSX.VarsityRace & JSXBase.HTMLAttributes<HTMLVarsityRaceElement>;
            "varsity-total-score": LocalJSX.VarsityTotalScore & JSXBase.HTMLAttributes<HTMLVarsityTotalScoreElement>;
            "varsity-upcoming": LocalJSX.VarsityUpcoming & JSXBase.HTMLAttributes<HTMLVarsityUpcomingElement>;
            "varsity-weather": LocalJSX.VarsityWeather & JSXBase.HTMLAttributes<HTMLVarsityWeatherElement>;
            "video-banner": LocalJSX.VideoBanner & JSXBase.HTMLAttributes<HTMLVideoBannerElement>;
            "video-embed": LocalJSX.VideoEmbed & JSXBase.HTMLAttributes<HTMLVideoEmbedElement>;
            "video-gallery": LocalJSX.VideoGallery & JSXBase.HTMLAttributes<HTMLVideoGalleryElement>;
            "video-gallery-stacked": LocalJSX.VideoGalleryStacked & JSXBase.HTMLAttributes<HTMLVideoGalleryStackedElement>;
        }
    }
}
